definitions:
  steps:
    - step: &node-prepare
        name: Prepare node environment
        image: node:18.12.1
        caches:
          - node
        script:
          - npm install
    - step: &test-react
        name: Test React App
        image: node:19
        caches:
          - node
        script:
          - npm test
    - step: &build-react
        name: Build React App
        image: node:18
        caches:
          - node
        script:
          - npm run build
        artifacts:
          - build/**
    - step: &build-java
        name: Build JAR file
        image: maven:3-amazoncorretto-17
        caches:
          - gradle
        script:
          - cd builder
          - bash ./gradlew jar
        artifacts:
          - builder/build/**
    - step: &sign-publish
        image: maven:3-amazoncorretto-17
        name: Publish artifact
        caches:
          - gradle
        script:
          - cd builder
          - export GPG_TTY=$(tty)
          - yum install openssl11 gnupg -y
          - openssl11 aes-256-cbc -a -k "$SIGNING_PWD" -in private-key.gpg.enc -out private-key.gpg -d
          - gpg --import private-key.gpg
          - printf "signing.keyId=$GPG_KEY\nsigning.password=$GPG_PASSWORD\nsigning.secretKeyRingFile=$BITBUCKET_CLONE_DIR/private-key.gpg" > ~/.gradle/gradle.properties
          - bash ./gradlew publish

pipelines:
  branches:
    master:
      - step: *node-prepare
      - parallel:
          - step: *build-react
          - step: *test-react
      - step: *build-java
      - step: *sign-publish
