definitions:
  services:
    java-builder:
      image:
        name: maven:3-amazoncorretto-17
  steps:
    - step: &node-prepare
        name: Prepare node environment
        image: node:18.12.1
        caches:
          - node
        scripts:
          - npm install
    - step: &build-react
        name: Build React App
        image: node:18.12.1
        caches:
          - node
        script:
          - npm run build
        artifacts:
          - build/**
    - step: &build-java
        name: Build JAR file
        services:
          - java-builder
        caches:
          - gradle
        script:
          - cd builder
          - export GPG_TTY=$(tty)
          - yum install openssl11 gnupg -y
          - openssl11 aes-256-cbc -a -k "$SIGNING_PWD" -in private-key.gpg.enc -out private-key.gpg -d
          - gpg --import private-key.gpg
          - printf "signing.keyId=$GPG_KEY\nsigning.password=$GPG_PASSWORD\nsigning.secretKeyRingFile=$BITBUCKET_CLONE_DIR/private-key.gpg" > ~/.gradle/gradle.properties
          - bash ./gradlew jar

pipelines:
  branches:
    master:
      - step: *node-prepare
      - step: *build-react
      - step: *build-java
